import "~/styles/globals.css";
import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/Navbar";
import SidebarClient from "./_components/sidebar";


export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html >
      <body>
        <TRPCReactProvider>
          <div className="flex w-full">
            <div className="w-72">
              <SidebarClient />
            </div>
            <div className="w-full">
              <Navbar />
              {children}
            </div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
